version: '3.8'

services:
  verifier:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-verifier-endpoint:0.8.0
    container_name: verifier-backend
    restart: unless-stopped
    environment:
      VERIFIER_PUBLICURL: "https://srv132427807.host/api"
      VERIFIER_RESPONSE_MODE: "DirectPost"
    networks:
      - eudi-net

  verifier-ui:
    image: ghcr.io/eu-digital-identity-wallet/eudi-web-verifier:latest
    container_name: verifier-ui
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=""
      - HOST_API="https://srv132427807.host/api"
    networks:
      - eudi-net

networks:
  eudi-net:
    driver: bridge
